(window.webpackJsonp=window.webpackJsonp||[]).push([[55],{214:function(e,t,n){"use strict";n.r(t);var a=n(0),r=Object(a.a)({},function(){var e=this,t=e.$createElement,n=e._self._c||t;return n("div",{staticClass:"content"},[e._m(0),e._v(" "),n("p",[e._v("In this article, you will learn about Exception Handling in C++ and which handle run time error.")]),e._v(" "),e._m(1),e._v(" "),n("p",[e._v("C++ exception handling is built upon three keywords: try, catch, and throw.")]),e._v(" "),n("p",[e._v("Exception Handling vs Traditional Error Handling")]),e._v(" "),n("p",[e._v("Following are main advantages of exception handling over traditional error handling.")]),e._v(" "),e._m(2),e._v(" "),n("p",[e._v("In traditional error handling codes, there are always if else conditions to handle errors. These conditions and the code to handle errors get mixed up with the normal flow. This makes the code less readable and maintainable. With try catch blocks, the code for error handling becomes separate from the normal flow.")]),e._v(" "),n("InPageAds"),e._v(" "),e._m(3),e._v(" "),n("p",[e._v("A function can throw many exceptions, but may choose to handle some of them. The other exceptions which are thrown, but not caught can be handled by caller. If the caller chooses not to catch them, then the exceptions are handled by caller of the caller.\nIn C++, a function can specify the exceptions that it throws using the throw keyword. The caller of this function must handle the exception in some way (either by specifying it again or catching it)")]),e._v(" "),e._m(4),e._v(" "),n("p",[e._v("In C++, both basic types and objects can be thrown as exception. We can create a hierarchy of exception objects, group exceptions in namespaces or classes, categorize them according to types.")]),e._v(" "),e._m(5),e._v(" "),n("p",[e._v("The error handling mechanism perform following task :")]),e._v(" "),e._m(6),e._v(" "),n("img",{attrs:{src:"https://1.bp.blogspot.com/-7-cFx7t0GQg/WPOHfF4FoEI/AAAAAAAAAi8/M8CVmjoGzssNx3vB8pL7nYptUADiNv3vACPcB/s1600/What%2Bis%2BException%2BHandling%2Bin%2BC%252B%252B%2B1.jpg"}}),e._v(" "),e._m(7),e._v(" "),n("p",[e._v('A try/catch block is placed around the code for which particular exception will be analysed and detected.It is followed by one or more catch blocks . The try block doesn\'t define how we are handling an exception but it merely tells the program , "if you see an exception in the following code , grab it". If the try block detects exception , the exception is thrown to catch block using throw keyword and program control also transfer to catch block , it never returns to try blocks again. If no error is found within try block , catch block is escaped .')]),e._v(" "),n("p",[e._v("Syntax:")]),e._v(" "),e._m(8),e._m(9),e._v(" "),n("p",[e._v("An exception is thrown in a particular catch block using throw keyword. It can throw object of different types , known as exception objects.")]),e._v(" "),n("p",[e._v("When try blocks is executed , whenever exceptions are found they are thrown through throw blocks and the program leaves the try block and enters into the catch blocks . If type of object thrown in try block match the argument type in the catch statement ,\nthe catch block are executed to handle those exception . If no match catch are found , then program is aborted with the help of abort() function which is invoked by default\nCatch Block")]),e._v(" "),n("p",[e._v("The catch block following the try block catches any exception. You can specify what type of exception you want to catch and this is determined by the exception declaration that appears in parentheses following the keyword catch.")]),e._v(" "),n("p",[e._v("Syntax")]),e._v(" "),e._m(10),e._m(11),e._v(" "),n("p",[e._v("If a catch block cannot handle the particular exception it has caught, you can rethrow the exception. The rethrow expression (throw without assignment_expression) causes the originally thrown object to be rethrown.")]),e._v(" "),n("p",[e._v("Because the exception has already been caught at the scope in which the rethrow expression occurs, it is rethrown out to the next dynamically enclosing try block. Therefore, it cannot be handled by catch blocks at the scope in which the rethrow expression occurred. Any catch blocks for the dynamically enclosing try block have an opportunity to catch the exception.")])],1)},[function(){var e=this.$createElement,t=this._self._c||e;return t("h1",{attrs:{id:"exception-handling"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#exception-handling","aria-hidden":"true"}},[this._v("#")]),this._v(" Exception Handling")])},function(){var e=this.$createElement,t=this._self._c||e;return t("h2",{attrs:{id:"exception-handling-is-the-mechanism-that-separate-the-code-that-detects-and-handle-exceptions-at-run-time-from-rest-of-program"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#exception-handling-is-the-mechanism-that-separate-the-code-that-detects-and-handle-exceptions-at-run-time-from-rest-of-program","aria-hidden":"true"}},[this._v("#")]),this._v(" Exception Handling is the mechanism that separate the code that detects and handle exceptions at run time from rest of program")])},function(){var e=this.$createElement,t=this._self._c||e;return t("h3",{attrs:{id:"_1-separation-of-error-handling-code-from-normal-code"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_1-separation-of-error-handling-code-from-normal-code","aria-hidden":"true"}},[this._v("#")]),this._v(" 1. Separation of Error Handling code from Normal Code:")])},function(){var e=this.$createElement,t=this._self._c||e;return t("h3",{attrs:{id:"_2-functions-methods-can-handle-any-exceptions-they-choose"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_2-functions-methods-can-handle-any-exceptions-they-choose","aria-hidden":"true"}},[this._v("#")]),this._v(" 2. Functions/Methods can handle any exceptions they choose:")])},function(){var e=this.$createElement,t=this._self._c||e;return t("h3",{attrs:{id:"_3-grouping-of-error-types"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_3-grouping-of-error-types","aria-hidden":"true"}},[this._v("#")]),this._v(" 3.  Grouping of Error Types:")])},function(){var e=this.$createElement,t=this._self._c||e;return t("h2",{attrs:{id:"exception-handling-model"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#exception-handling-model","aria-hidden":"true"}},[this._v("#")]),this._v(" Exception Handling Model")])},function(){var e=this.$createElement,t=this._self._c||e;return t("ul",[t("li",[this._v("Find the problem (Hit the Exception)")]),this._v(" "),t("li",[this._v("Inform that error has occured (Throw the exception)")]),this._v(" "),t("li",[this._v("Receive the error information (Catch the exception)")]),this._v(" "),t("li",[this._v("Take corrective ations (Handle the exception)")])])},function(){var e=this.$createElement,t=this._self._c||e;return t("h2",{attrs:{id:"try-block"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#try-block","aria-hidden":"true"}},[this._v("#")]),this._v(" Try Block")])},function(){var e=this,t=e.$createElement,n=e._self._c||t;return n("div",{staticClass:"language-c line-numbers-mode"},[n("pre",{pre:!0,attrs:{class:"language-c"}},[n("code",[e._v("try\n"),n("span",{attrs:{class:"token punctuation"}},[e._v("{")]),e._v("\n"),n("span",{attrs:{class:"token comment"}},[e._v("//code to be monitered.")]),e._v("\n"),n("span",{attrs:{class:"token punctuation"}},[e._v("}")]),e._v("\n\n")])]),e._v(" "),n("div",{staticClass:"line-numbers-wrapper"},[n("span",{staticClass:"line-number"},[e._v("1")]),n("br"),n("span",{staticClass:"line-number"},[e._v("2")]),n("br"),n("span",{staticClass:"line-number"},[e._v("3")]),n("br"),n("span",{staticClass:"line-number"},[e._v("4")]),n("br"),n("span",{staticClass:"line-number"},[e._v("5")]),n("br")])])},function(){var e=this.$createElement,t=this._self._c||e;return t("h2",{attrs:{id:"throw-block"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#throw-block","aria-hidden":"true"}},[this._v("#")]),this._v(" Throw Block")])},function(){var e=this,t=e.$createElement,n=e._self._c||t;return n("div",{staticClass:"language-c line-numbers-mode"},[n("pre",{pre:!0,attrs:{class:"language-c"}},[n("code",[e._v("catch "),n("span",{attrs:{class:"token punctuation"}},[e._v("(")]),n("span",{attrs:{class:"token punctuation"}},[e._v(")")]),e._v("\n"),n("span",{attrs:{class:"token punctuation"}},[e._v("{")]),e._v("\n"),n("span",{attrs:{class:"token comment"}},[e._v("//block of statement that handles the exception")]),e._v("\n"),n("span",{attrs:{class:"token punctuation"}},[e._v("}")]),e._v("\n")])]),e._v(" "),n("div",{staticClass:"line-numbers-wrapper"},[n("span",{staticClass:"line-number"},[e._v("1")]),n("br"),n("span",{staticClass:"line-number"},[e._v("2")]),n("br"),n("span",{staticClass:"line-number"},[e._v("3")]),n("br"),n("span",{staticClass:"line-number"},[e._v("4")]),n("br")])])},function(){var e=this.$createElement,t=this._self._c||e;return t("h2",{attrs:{id:"rethrowing-an-exception"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#rethrowing-an-exception","aria-hidden":"true"}},[this._v("#")]),this._v(" Rethrowing an Exception")])}],!1,null,null,null);r.options.__file="exception-handling-c-language.md";t.default=r.exports}}]);